# Generated by Django 4.1.2 on 2022-10-15 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('set', models.CharField(max_length=64)),
                ('is_foil', models.BooleanField(null=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
            ],
        ),
    ]
